spring.datasource:
  url: "jdbc:postgresql://localhost:5432/gb_shop"
  username: "geek"
  password: "geek"
spring:
  mvc:
    format:
      date: "yyyy-MM-dd"
    pathmatch:
      matching-strategy: ant_path_matcher
